//! Tests for map column support
//!
//! Tests reading and writing Parquet files with map columns.

const std = @import("std");
const parquet = @import("../lib.zig");

const Reader = parquet.Reader;
const Writer = parquet.Writer;
const ColumnDef = parquet.ColumnDef;
const Optional = parquet.Optional;
// Use writer's MapEntry for writing (and reading types are compatible via assembly)
const WriterMapEntry = @import("../core/map_encoder.zig").MapEntry;

// =============================================================================
// Read tests
// =============================================================================

test "read map_string_int.parquet" {
    const allocator = std.testing.allocator;

    // Open the file generated by PyArrow
    const file = std.fs.cwd().openFile("../test-files-arrow/nested/map_string_int.parquet", .{}) catch |err| {
        std.debug.print("Skipping test - file not found: {}\n", .{err});
        return;
    };
    defer file.close();

    var reader = try parquet.openFile(allocator, file);
    defer reader.deinit();

    // File has 5 rows:
    // Row 0: {"a": 1, "b": 2}
    // Row 1: {"c": 3}
    // Row 2: {} (empty map)
    // Row 3: null
    // Row 4: {"d": 4, "e": 5, "f": 6}

    // Read the map column (key column is at index 0, value is at index 1)
    const maps = try reader.readMapColumn(0, []const u8, i32);
    defer reader.freeMapColumn([]const u8, i32, maps);

    try std.testing.expectEqual(@as(usize, 5), maps.len);

    // Row 0: {"a": 1, "b": 2}
    try std.testing.expect(!maps[0].isNull());
    const row0 = maps[0].value;
    try std.testing.expectEqual(@as(usize, 2), row0.len);
    try std.testing.expectEqualStrings("a", row0[0].key);
    try std.testing.expectEqual(@as(i32, 1), row0[0].value.value);
    try std.testing.expectEqualStrings("b", row0[1].key);
    try std.testing.expectEqual(@as(i32, 2), row0[1].value.value);

    // Row 1: {"c": 3}
    try std.testing.expect(!maps[1].isNull());
    const row1 = maps[1].value;
    try std.testing.expectEqual(@as(usize, 1), row1.len);
    try std.testing.expectEqualStrings("c", row1[0].key);
    try std.testing.expectEqual(@as(i32, 3), row1[0].value.value);

    // Row 2: {} (empty map)
    try std.testing.expect(!maps[2].isNull());
    try std.testing.expectEqual(@as(usize, 0), maps[2].value.len);

    // Row 3: null
    try std.testing.expect(maps[3].isNull());

    // Row 4: {"d": 4, "e": 5, "f": 6}
    try std.testing.expect(!maps[4].isNull());
    const row4 = maps[4].value;
    try std.testing.expectEqual(@as(usize, 3), row4.len);
    try std.testing.expectEqualStrings("d", row4[0].key);
    try std.testing.expectEqual(@as(i32, 4), row4[0].value.value);
    try std.testing.expectEqualStrings("e", row4[1].key);
    try std.testing.expectEqual(@as(i32, 5), row4[1].value.value);
    try std.testing.expectEqualStrings("f", row4[2].key);
    try std.testing.expectEqual(@as(i32, 6), row4[2].value.value);
}

// =============================================================================
// Round-trip tests
// =============================================================================

test "write and read simple map" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_simple.parquet";

    // Write a parquet file with a map column
    {
        const file = try tmp_dir.dir.createFile(file_path, .{});
        defer file.close();

        // Define columns
        const columns = [_]ColumnDef{
            ColumnDef.mapStringInt32("attributes", true),
        };

        var writer = try parquet.writeToFile(allocator, file, &columns);
        defer writer.deinit();

        // Map data: [{a: 1, b: 2}, {c: 3}]
        const entries0 = [_]WriterMapEntry([]const u8, i32){
            .{ .key = "a", .value = .{ .value = 1 } },
            .{ .key = "b", .value = .{ .value = 2 } },
        };
        const entries1 = [_]WriterMapEntry([]const u8, i32){
            .{ .key = "c", .value = .{ .value = 3 } },
        };
        const maps = [_]Optional([]const WriterMapEntry([]const u8, i32)){
            .{ .value = &entries0 },
            .{ .value = &entries1 },
        };

        try writer.writeMapColumnStringInt32(0, &maps);
        try writer.close();
    }

    // Read it back
    {
        const file = try tmp_dir.dir.openFile(file_path, .{});
        defer file.close();

        var reader = try parquet.openFile(allocator, file);
        defer reader.deinit();

        const maps = try reader.readMapColumn(0, []const u8, i32);
        defer reader.freeMapColumn([]const u8, i32, maps);

        try std.testing.expectEqual(@as(usize, 2), maps.len);

        // Row 0: {a: 1, b: 2}
        try std.testing.expect(!maps[0].isNull());
        const row0 = maps[0].value;
        try std.testing.expectEqual(@as(usize, 2), row0.len);
        try std.testing.expectEqualStrings("a", row0[0].key);
        try std.testing.expectEqual(@as(i32, 1), row0[0].value.value);
        try std.testing.expectEqualStrings("b", row0[1].key);
        try std.testing.expectEqual(@as(i32, 2), row0[1].value.value);

        // Row 1: {c: 3}
        try std.testing.expect(!maps[1].isNull());
        const row1 = maps[1].value;
        try std.testing.expectEqual(@as(usize, 1), row1.len);
        try std.testing.expectEqualStrings("c", row1[0].key);
        try std.testing.expectEqual(@as(i32, 3), row1[0].value.value);
    }
}

test "write and read map with null values" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_null_values.parquet";

    // Write
    {
        const file = try tmp_dir.dir.createFile(file_path, .{});
        defer file.close();

        const columns = [_]ColumnDef{
            ColumnDef.mapStringInt32("data", true),
        };

        var writer = try parquet.writeToFile(allocator, file, &columns);
        defer writer.deinit();

        // Map data: [{a: 1, b: null, c: 3}]
        const entries0 = [_]WriterMapEntry([]const u8, i32){
            .{ .key = "a", .value = .{ .value = 1 } },
            .{ .key = "b", .value = .{ .null_value = {} } },
            .{ .key = "c", .value = .{ .value = 3 } },
        };
        const maps = [_]Optional([]const WriterMapEntry([]const u8, i32)){
            .{ .value = &entries0 },
        };

        try writer.writeMapColumnStringInt32(0, &maps);
        try writer.close();
    }

    // Read
    {
        const file = try tmp_dir.dir.openFile(file_path, .{});
        defer file.close();

        var reader = try parquet.openFile(allocator, file);
        defer reader.deinit();

        const maps = try reader.readMapColumn(0, []const u8, i32);
        defer reader.freeMapColumn([]const u8, i32, maps);

        try std.testing.expectEqual(@as(usize, 1), maps.len);

        const row0 = maps[0].value;
        try std.testing.expectEqual(@as(usize, 3), row0.len);

        try std.testing.expectEqualStrings("a", row0[0].key);
        try std.testing.expectEqual(@as(i32, 1), row0[0].value.value);

        try std.testing.expectEqualStrings("b", row0[1].key);
        try std.testing.expect(row0[1].value.isNull());

        try std.testing.expectEqualStrings("c", row0[2].key);
        try std.testing.expectEqual(@as(i32, 3), row0[2].value.value);
    }
}

test "write and read map with null and empty maps" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_null_empty.parquet";

    // Write
    {
        const file = try tmp_dir.dir.createFile(file_path, .{});
        defer file.close();

        const columns = [_]ColumnDef{
            ColumnDef.mapStringInt32("data", true),
        };

        var writer = try parquet.writeToFile(allocator, file, &columns);
        defer writer.deinit();

        // Map data: [{a: 1}, null, {}]
        const entries0 = [_]WriterMapEntry([]const u8, i32){
            .{ .key = "a", .value = .{ .value = 1 } },
        };
        const entries2 = [_]WriterMapEntry([]const u8, i32){};
        const maps = [_]Optional([]const WriterMapEntry([]const u8, i32)){
            .{ .value = &entries0 },
            .{ .null_value = {} },
            .{ .value = &entries2 },
        };

        try writer.writeMapColumnStringInt32(0, &maps);
        try writer.close();
    }

    // Read
    {
        const file = try tmp_dir.dir.openFile(file_path, .{});
        defer file.close();

        var reader = try parquet.openFile(allocator, file);
        defer reader.deinit();

        const maps = try reader.readMapColumn(0, []const u8, i32);
        defer reader.freeMapColumn([]const u8, i32, maps);

        try std.testing.expectEqual(@as(usize, 3), maps.len);

        // Row 0: {a: 1}
        try std.testing.expect(!maps[0].isNull());
        try std.testing.expectEqual(@as(usize, 1), maps[0].value.len);

        // Row 1: null
        try std.testing.expect(maps[1].isNull());

        // Row 2: {} (empty map)
        try std.testing.expect(!maps[2].isNull());
        try std.testing.expectEqual(@as(usize, 0), maps[2].value.len);
    }
}

test "write and read large map column (multi-page accumulator test)" {
    // This test verifies that the map column reader correctly accumulates values
    // when processing large datasets. While this test may fit in a single page
    // when written by zig-parquet, the accumulator-based reading logic in
    // decodeMapColumn is essential for reading multi-page maps from other writers
    // (e.g., Spark, PyArrow with large datasets).
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "large_map.parquet";

    // Write phase: create many rows with varying map sizes
    {
        const file = try tmp_dir.dir.createFile(file_path, .{ .read = true });
        defer file.close();

        const columns = [_]ColumnDef{
            ColumnDef.map("data", .byte_array, .int32, true),
        };

        var writer = try parquet.writeToFile(allocator, file, &columns);
        defer writer.deinit();

        // Generate 100 rows with varying map sizes (0-10 entries each)
        // Total ~500 key-value pairs to exercise accumulator logic
        var maps: [100]Optional([]const WriterMapEntry([]const u8, i32)) = undefined;
        var all_entries: [1000]WriterMapEntry([]const u8, i32) = undefined;
        var entry_idx: usize = 0;

        // Pre-generate all keys (we need stable string references)
        var keys: [1000][8]u8 = undefined;
        for (0..1000) |i| {
            const key_slice = std.fmt.bufPrint(&keys[i], "key{d:04}", .{i}) catch unreachable;
            _ = key_slice;
        }

        for (0..100) |row| {
            const num_entries = row % 11; // 0-10 entries per row
            if (num_entries == 0) {
                // Empty map (not null)
                maps[row] = .{ .value = &[_]WriterMapEntry([]const u8, i32){} };
            } else {
                const start = entry_idx;
                for (0..num_entries) |j| {
                    all_entries[entry_idx] = .{
                        .key = keys[entry_idx][0..std.fmt.count("key{d:04}", .{entry_idx})],
                        .value = .{ .value = @intCast(row * 100 + j) },
                    };
                    entry_idx += 1;
                }
                maps[row] = .{ .value = all_entries[start..entry_idx] };
            }
        }

        try writer.writeMapColumnStringInt32(0, &maps);
        try writer.close();
    }

    // Read phase: verify all data
    {
        const file = try tmp_dir.dir.openFile(file_path, .{});
        defer file.close();

        var reader = try parquet.openFile(allocator, file);
        defer reader.deinit();

        const read_maps = try reader.readMapColumn(0, []const u8, i32);
        defer reader.freeMapColumn([]const u8, i32, read_maps);

        try std.testing.expectEqual(@as(usize, 100), read_maps.len);

        // Verify a sample of rows
        // Row 0: 0 entries (empty)
        try std.testing.expect(!read_maps[0].isNull());
        try std.testing.expectEqual(@as(usize, 0), read_maps[0].value.len);

        // Row 5: 5 entries
        try std.testing.expect(!read_maps[5].isNull());
        try std.testing.expectEqual(@as(usize, 5), read_maps[5].value.len);

        // Row 10: 10 entries
        try std.testing.expect(!read_maps[10].isNull());
        try std.testing.expectEqual(@as(usize, 10), read_maps[10].value.len);

        // Verify all row entry counts match expected pattern
        for (read_maps, 0..) |map_opt, row| {
            const expected_entries = row % 11;
            try std.testing.expect(!map_opt.isNull());
            try std.testing.expectEqual(expected_entries, map_opt.value.len);
        }
    }

}

// =============================================================================
// New type combination round-trip tests
// =============================================================================

test "round-trip map string-to-f64" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_string_f64.parquet";

    {
        const file = try tmp_dir.dir.createFile(file_path, .{});
        defer file.close();

        const columns = [_]ColumnDef{
            ColumnDef.mapStringFloat64("scores", true),
        };

        var writer = try parquet.writeToFile(allocator, file, &columns);
        defer writer.deinit();

        const entries0 = [_]WriterMapEntry([]const u8, f64){
            .{ .key = "math", .value = .{ .value = 95.5 } },
            .{ .key = "science", .value = .{ .value = 88.25 } },
        };
        const entries1 = [_]WriterMapEntry([]const u8, f64){
            .{ .key = "english", .value = .{ .value = 72.0 } },
            .{ .key = "history", .value = .{ .null_value = {} } },
        };
        const maps = [_]Optional([]const WriterMapEntry([]const u8, f64)){
            .{ .value = &entries0 },
            .{ .value = &entries1 },
            .{ .null_value = {} },
        };

        try writer.writeMapColumn([]const u8, f64, 0, &maps);
        try writer.close();
    }

    {
        const file = try tmp_dir.dir.openFile(file_path, .{});
        defer file.close();

        var reader = try parquet.openFile(allocator, file);
        defer reader.deinit();

        const maps = try reader.readMapColumn(0, []const u8, f64);
        defer reader.freeMapColumn([]const u8, f64, maps);

        try std.testing.expectEqual(@as(usize, 3), maps.len);

        const row0 = maps[0].value;
        try std.testing.expectEqual(@as(usize, 2), row0.len);
        try std.testing.expectEqualStrings("math", row0[0].key);
        try std.testing.expectEqual(@as(f64, 95.5), row0[0].value.value);
        try std.testing.expectEqualStrings("science", row0[1].key);
        try std.testing.expectEqual(@as(f64, 88.25), row0[1].value.value);

        const row1 = maps[1].value;
        try std.testing.expectEqual(@as(usize, 2), row1.len);
        try std.testing.expectEqualStrings("english", row1[0].key);
        try std.testing.expectEqual(@as(f64, 72.0), row1[0].value.value);
        try std.testing.expectEqualStrings("history", row1[1].key);
        try std.testing.expect(row1[1].value.isNull());

        try std.testing.expect(maps[2].isNull());
    }
}

test "round-trip map string-to-bool" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_string_bool.parquet";

    {
        const file = try tmp_dir.dir.createFile(file_path, .{});
        defer file.close();

        const columns = [_]ColumnDef{
            ColumnDef.mapStringBool("flags", true),
        };

        var writer = try parquet.writeToFile(allocator, file, &columns);
        defer writer.deinit();

        const entries0 = [_]WriterMapEntry([]const u8, bool){
            .{ .key = "active", .value = .{ .value = true } },
            .{ .key = "verified", .value = .{ .value = false } },
        };
        const entries1 = [_]WriterMapEntry([]const u8, bool){
            .{ .key = "admin", .value = .{ .value = true } },
            .{ .key = "deleted", .value = .{ .null_value = {} } },
        };
        const maps = [_]Optional([]const WriterMapEntry([]const u8, bool)){
            .{ .value = &entries0 },
            .{ .value = &entries1 },
        };

        try writer.writeMapColumn([]const u8, bool, 0, &maps);
        try writer.close();
    }

    {
        const file = try tmp_dir.dir.openFile(file_path, .{});
        defer file.close();

        var reader = try parquet.openFile(allocator, file);
        defer reader.deinit();

        const maps = try reader.readMapColumn(0, []const u8, bool);
        defer reader.freeMapColumn([]const u8, bool, maps);

        try std.testing.expectEqual(@as(usize, 2), maps.len);

        const row0 = maps[0].value;
        try std.testing.expectEqual(@as(usize, 2), row0.len);
        try std.testing.expectEqualStrings("active", row0[0].key);
        try std.testing.expectEqual(true, row0[0].value.value);
        try std.testing.expectEqualStrings("verified", row0[1].key);
        try std.testing.expectEqual(false, row0[1].value.value);

        const row1 = maps[1].value;
        try std.testing.expectEqual(@as(usize, 2), row1.len);
        try std.testing.expectEqualStrings("admin", row1[0].key);
        try std.testing.expectEqual(true, row1[0].value.value);
        try std.testing.expectEqualStrings("deleted", row1[1].key);
        try std.testing.expect(row1[1].value.isNull());
    }
}

test "round-trip map i32-to-string" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_i32_string.parquet";

    {
        const file = try tmp_dir.dir.createFile(file_path, .{});
        defer file.close();

        const columns = [_]ColumnDef{
            ColumnDef.mapInt32String("labels", true),
        };

        var writer = try parquet.writeToFile(allocator, file, &columns);
        defer writer.deinit();

        const entries0 = [_]WriterMapEntry(i32, []const u8){
            .{ .key = 1, .value = .{ .value = "one" } },
            .{ .key = 2, .value = .{ .value = "two" } },
        };
        const entries1 = [_]WriterMapEntry(i32, []const u8){
            .{ .key = 100, .value = .{ .value = "hundred" } },
            .{ .key = 200, .value = .{ .null_value = {} } },
        };
        const maps = [_]Optional([]const WriterMapEntry(i32, []const u8)){
            .{ .value = &entries0 },
            .{ .value = &entries1 },
            .{ .null_value = {} },
        };

        try writer.writeMapColumn(i32, []const u8, 0, &maps);
        try writer.close();
    }

    {
        const file = try tmp_dir.dir.openFile(file_path, .{});
        defer file.close();

        var reader = try parquet.openFile(allocator, file);
        defer reader.deinit();

        const maps = try reader.readMapColumn(0, i32, []const u8);
        defer reader.freeMapColumn(i32, []const u8, maps);

        try std.testing.expectEqual(@as(usize, 3), maps.len);

        const row0 = maps[0].value;
        try std.testing.expectEqual(@as(usize, 2), row0.len);
        try std.testing.expectEqual(@as(i32, 1), row0[0].key);
        try std.testing.expectEqualStrings("one", row0[0].value.value);
        try std.testing.expectEqual(@as(i32, 2), row0[1].key);
        try std.testing.expectEqualStrings("two", row0[1].value.value);

        const row1 = maps[1].value;
        try std.testing.expectEqual(@as(usize, 2), row1.len);
        try std.testing.expectEqual(@as(i32, 100), row1[0].key);
        try std.testing.expectEqualStrings("hundred", row1[0].value.value);
        try std.testing.expectEqual(@as(i32, 200), row1[1].key);
        try std.testing.expect(row1[1].value.isNull());

        try std.testing.expect(maps[2].isNull());
    }
}

test "round-trip map string-to-i64" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_string_i64.parquet";

    {
        const file = try tmp_dir.dir.createFile(file_path, .{});
        defer file.close();

        const columns = [_]ColumnDef{
            ColumnDef.mapStringInt64("timestamps", true),
        };

        var writer = try parquet.writeToFile(allocator, file, &columns);
        defer writer.deinit();

        const entries0 = [_]WriterMapEntry([]const u8, i64){
            .{ .key = "created", .value = .{ .value = 1700000000000 } },
            .{ .key = "updated", .value = .{ .value = 1700001000000 } },
        };
        const entries1 = [_]WriterMapEntry([]const u8, i64){
            .{ .key = "deleted", .value = .{ .null_value = {} } },
        };
        const maps = [_]Optional([]const WriterMapEntry([]const u8, i64)){
            .{ .value = &entries0 },
            .{ .value = &entries1 },
        };

        try writer.writeMapColumn([]const u8, i64, 0, &maps);
        try writer.close();
    }

    {
        const file = try tmp_dir.dir.openFile(file_path, .{});
        defer file.close();

        var reader = try parquet.openFile(allocator, file);
        defer reader.deinit();

        const maps = try reader.readMapColumn(0, []const u8, i64);
        defer reader.freeMapColumn([]const u8, i64, maps);

        try std.testing.expectEqual(@as(usize, 2), maps.len);

        const row0 = maps[0].value;
        try std.testing.expectEqual(@as(usize, 2), row0.len);
        try std.testing.expectEqualStrings("created", row0[0].key);
        try std.testing.expectEqual(@as(i64, 1700000000000), row0[0].value.value);
        try std.testing.expectEqualStrings("updated", row0[1].key);
        try std.testing.expectEqual(@as(i64, 1700001000000), row0[1].value.value);

        const row1 = maps[1].value;
        try std.testing.expectEqual(@as(usize, 1), row1.len);
        try std.testing.expectEqualStrings("deleted", row1[0].key);
        try std.testing.expect(row1[0].value.isNull());
    }
}

test "round-trip map string-to-f32" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_string_f32.parquet";

    {
        const file = try tmp_dir.dir.createFile(file_path, .{});
        defer file.close();

        const columns = [_]ColumnDef{
            ColumnDef.mapStringFloat32("weights", true),
        };

        var writer = try parquet.writeToFile(allocator, file, &columns);
        defer writer.deinit();

        const entries0 = [_]WriterMapEntry([]const u8, f32){
            .{ .key = "alpha", .value = .{ .value = 0.5 } },
            .{ .key = "beta", .value = .{ .value = 1.25 } },
        };
        const maps = [_]Optional([]const WriterMapEntry([]const u8, f32)){
            .{ .value = &entries0 },
            .{ .null_value = {} },
        };

        try writer.writeMapColumn([]const u8, f32, 0, &maps);
        try writer.close();
    }

    {
        const file = try tmp_dir.dir.openFile(file_path, .{});
        defer file.close();

        var reader = try parquet.openFile(allocator, file);
        defer reader.deinit();

        const maps = try reader.readMapColumn(0, []const u8, f32);
        defer reader.freeMapColumn([]const u8, f32, maps);

        try std.testing.expectEqual(@as(usize, 2), maps.len);

        const row0 = maps[0].value;
        try std.testing.expectEqual(@as(usize, 2), row0.len);
        try std.testing.expectEqualStrings("alpha", row0[0].key);
        try std.testing.expectEqual(@as(f32, 0.5), row0[0].value.value);
        try std.testing.expectEqualStrings("beta", row0[1].key);
        try std.testing.expectEqual(@as(f32, 1.25), row0[1].value.value);

        try std.testing.expect(maps[1].isNull());
    }
}
